### ISSUE TITLE
Could not find module 'KAlert' for architecture 'arm64'; found: x86_64-apple-ios-simulator, x86_64

### ISSUE THREAD

**Issue by asn111** [krishnads/KCustomAlert#2]
I don't know why I am getting this issue, I am using swift 4.2 and xCode 10.2.1

**Comment by krishnads** [comment]
If you are getting error by using framework file then simply drag CustomAlert folder into your project and use it by the way i have described. I will look into this.

**Comment by asn111** [comment]
I did it the same way you told in readme file.but it didn't worked

**Comment by krishnads** [comment]
Remove Framework file and try again
