### ISSUE TITLE
adding tap gesture to dismiss alert

### ISSUE THREAD

**Issue by mobh13** [krishnads/KCustomAlert#3]
can this be done I tried but could not do it if user clicks on anything besides the button it dismiss the alert

**Comment by krishnads** [comment]
Yes, you can!

Simply add a tap gesture on view of customAlertController and dismiss controller in the selector method.

**Comment by mobh13** [comment]
sorry I meant anything besides the button and the alert itself

**Comment by krishnads** [comment]
Its very simple bro---

Use following code in CustomAlertVC class and you are done....


    `override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        
        let tapMainView = UITapGestureRecognizer(target: self, action: #selector(tapAction))
        tapMainView.numberOfTapsRequired = 1
        self.view.addGestureRecognizer(tapMainView)
        
        
        let tapContainerView = UITapGestureRecognizer(target: self, action: #selector(tapAction))
        tapContainerView.numberOfTapsRequired = 1
        self.view.addGestureRecognizer(tapContainerView)
    }
    
    @objc func tapAction() {
        self.dismiss(animated: true, completion: nil)
    }
`

**Comment by mobh13** [comment]
thank you very much it worked
